FROM php:8.3-apache

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libbz2-dev \
        libcurl4-openssl-dev \
        libicu-dev \
        libonig-dev \
        libpng-dev \
        libzip-dev \
        unzip \
    && a2enmod rewrite \
    && docker-php-ext-configure gd \
    && docker-php-ext-install -j"$(nproc)" \
        bz2 \
        curl \
        gd \
        intl \
        mbstring \
        pdo_mysql \
        zip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

WORKDIR /var/www/html
